# Generated by Django 4.1 on 2022-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BrBadQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote_id", models.IntegerField()),
                ("quote", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=500)),
                ("series", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quotes from The Breaking Bad",
                "verbose_name_plural": "Quotes from The Breaking Bad",
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="SimpsonQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.CharField(max_length=500)),
                ("character", models.CharField(max_length=500)),
                ("image", models.CharField(max_length=500)),
                ("characterDirection", models.CharField(max_length=500)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quotes from The Simpson",
                "verbose_name_plural": "Quotes from The  Simpson",
                "ordering": ["created"],
            },
        ),
    ]
